apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: ecom
deploy:
  kubectl:
    manifests:
    - infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: kishorenewton/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
