POST  https://ticketing.dev/api/users/signin HTTP/1.1
content-type: application/json

{
    "email": "smaple",
    "password": ""
}

### 
POST  https://ticketing.dev/api/users/signin HTTP/1.1
content-type: application/json

{
    "email": "smaple@example.com",
    "password": "PasswordHere"
}