# Should throw an Error
POST https://ticketing.dev/api/users/signup HTTP/1.1
content-type: application/json

{
    "email": "skksks",
    "password": "1"
}

###

# Should create a user successfully 
POST https://ticketing.dev/api/users/signup HTTP/1.1
content-type: application/json

{
    "email": "example@gmail.com",
    "password": "PasswordHere"
}